### PR TITLE
Add Status methods

### PR DESCRIPTION
**Pull request by kevakil**
Includes:
- get_status()
- retweets()

### CODE REVIEW

**Comment by kevakil** [comment]
It seems to me that the dataframe for retweets always has a length one row less than the count. I couldn't figure out why this occurs, nor if it's important, but it seems worth mentioning.

**Comment by freddiev4** [comment]
@averagegohard Do you mean that if the count is 5, then there are 4 rows in total?
Or the numbers of the rows only go up to 4? If the latter, it's because DataFrame indices are zero-indexed.

Also, you should probably include the `retweet()` method. It's like `retweets()` but only gets a single retweet, given the ID of that retweet.

**Comment by wdm0006** [comment]
Thanks @FreddieV4 and @averagegohard, agreed regarding retweet() I missed that one when you asked the first time, sorry about that. 

The count discrepancy is peculiar.  Where is the count coming from, the twitter API response or the limit you're setting on the call?

**Comment by kevakil** [comment]
@wdm0006 - I only passed the value of count into self.client.retweets; I didn't use count besides that. (In my pr, in client.py, Line 836: data = self.client.retweets(id_, count)).

@FreddieV4 - If the count is 5, there are 4 rows in total. (if data is unaltered and count = 5, len(data) = 4)

Additionally, according to the tweepy API, retweets() should "Return up to 100 of the first retweets of the given tweet." I noticed that the maximum number of Status objects in data actually came out to 91, not 100 (if count > 91, len(data) = 91).

PS - The functionality of retweet() that @FreddieV4 described is actually that of get_status(). The function retweet() actually retweets the tweet with the given ID according to tweepy's API.
http://docs.tweepy.org/en/v3.5.0/api.html#API.get_status
http://docs.tweepy.org/en/v3.5.0/api.html#API.retweet

**Comment by freddiev4** [comment]
@averagegohard Ah ok `Retweets a tweet. Requires the id of the tweet you are retweeting.`. I completely glazed over that.

**Comment by wdm0006** [comment]
Ok, that makes sense.  Could you add a note in the docstring for retweets about this potential discrepancy, and then I can merge it in for now.  I think we are about to the point (when these two PRs get merged in) where I can clean things up and push the library and docs for a first formal release.

**Comment by kevakil** [comment]
Should I just manually add one to the count as well to ensure the user input for count actually returns the correct amount of objects?

**Comment by kevakil** [comment]
Some really weird stuff is going on.

The limit isn't always 91; I have seen it go down to 89 without changing any code in client.py. The only code I changed was in main. I used different status IDs with >100 retweets.

Another strange behavior I noticed: if count < 1, retweets returns 19 objects. Not sure if 19 is a set number or if it ranges.
Weird.

**Comment by wdm0006** [comment]
Very odd.  I would pass through the count the user provides as is, and leave a note in the doc string regarding the discrepancy.  It may be an issue in tweepy itself, we will have to investigate that more deeply I think.

**Comment by kevakil** [comment]
Ok, amended my commit and I listed the discrepancies in retweets(), should be ready for merge now.

**Comment by freddiev4** [comment]
If `count < 1` OR `count > 100` it seems to default to 19 retweets.

Tested it via the REST API "example request" https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid

**Pull request merged**
